flags: {}
extra-package-dbs: []
packages:
- '.'
- 'dep/market-model'
- 'dep/bitcoin-type'
- 'dep/gdax-adapter'
- 'dep/gdax-producer'
- 'dep/gdax-executor'

- location:
    git: https://github.com/dimitri-xyz/coinbase
    commit: c8fdb479b87160b16fd4692eb541b968edaaa8d3
  extra-dep: true

- location:
    git: https://github.com/dimitri-xyz/stego-uuid
    commit: 47f6bfa4660f6bee73581c71bce51dc09cf02a5c
  extra-dep: true

- location:
    git: https://github.com/dimitri-xyz/razao-base
    commit: e75322f1f1b4f477d36ca39b9cab8d4a78e86eee
  extra-dep: true

extra-deps:
- reactive-banana-1.1.0.1
- Crypto-4.2.5.1
- uuid-aeson-0.1.0.0
resolver: lts-8.3
