packages:
- '.'
- 'dep/market-interface'
- '../../../RAZAO/trading-strategy'
- '../../../RAZAO/coinbene-connector'  # FIX ME!
- '../../../RAZAO/coinbene-api'        # FIX ME!

# because of dep/market-interface (and for the tests)
- location:
    git: https://github.com/dimitri-xyz/market-model
    commit: 6bc68484bacddf1f8bd176583ed2813e5459b7f1
  extra-dep: true

- location:
    git: https://github.com/dimitri-xyz/razao-base
    commit: 5fc12c80aab9757f3aa1202d1abd4a7e172922df
  extra-dep: true

- location:
    git: https://github.com/HeinrichApfelmus/reactive-banana
    commit: 37d17de83bfa656ca20dc03457eeff0a2c33b6bf
  extra-dep: true
  subdirs:
  - reactive-banana

resolver: lts-13.1
