packages:
- '.'
- 'dep/market-interface'
- 'dep/coinbene-api'
- 'dep/coinbene-connector'
- '../trading-strategy'

# because of dep/market-interface (and for the tests)
- location:
    git: https://github.com/dimitri-xyz/market-model
    commit: ab1674058ee39e556a7fcade4de260ff1bdb503a
  extra-dep: true

- location:
    git: https://github.com/dimitri-xyz/razao-base
    commit: 5fc12c80aab9757f3aa1202d1abd4a7e172922df
  extra-dep: true

- location:
    git: https://github.com/HeinrichApfelmus/reactive-banana
    commit: 37d17de83bfa656ca20dc03457eeff0a2c33b6bf
  extra-dep: true
  subdirs:
  - reactive-banana

resolver: lts-13.1
